name: "ğŸš¨ Terraformã§æ¤œè¨¼ç’°å¢ƒã®ã‚¤ãƒ³ãƒ•ãƒ©ã‚’å‰Šé™¤"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'æ¤œè¨¼ç’°å¢ƒã‚’å‰Šé™¤ã—ã¾ã™ã€‚ ã€Œdevelopã€ã¨äººåŠ›ã—ã¦ãã ã•ã„ã€‚'
        required: true

run-name: Terraformå‰Šé™¤ ---> æ¤œè¨¼ç’°å¢ƒ

env:
  TF_VERSION: 1.8.0
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
  
  WORK_DIR: src/terraform/dev

  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: GitHub Actions
  SLACK_SUCCESS_MESSAGE: "æ¤œè¨¼ç’°å¢ƒã®Terrafomã®å‰Šé™¤ãŒå®Œäº†ã—ã¾ã—ãŸã€‚"
  SLACK_FAILURE_MESSAGE: "æ¤œè¨¼ç’°å¢ƒã®Terrafomã®å‰Šé™¤ã«å¤±æ•—ã—ã¾ã—ãŸ."

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      # å…¥åŠ›å€¤ãƒã‚§ãƒƒã‚¯
      - name: Target validate
        if: ${{ github.event.inputs.env != 'develop' }}
        run: exit 1
      
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Terraform init
        id: init
        working-directory: ${{ env.WORK_DIR }}
        run: terraform init

      - name: Terraform destroy
        id: destroy
        working-directory: ${{ env.WORK_DIR }}
        run: terraform destroy -auto-approve

      # Slacké€šçŸ¥
      - name: Slack notification on success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ env.SLACK_USERNAME }}
          SLACK_COLOR: good
          SLACK_MESSAGE: ${{ env.SLACK_SUCCESS_MESSAGE }}

      - name: Slack notification on failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ env.SLACK_USERNAME }}
          SLACK_COLOR: danger
          SLACK_MESSAGE: ${{ env.SLACK_FAILURE_MESSAGE }}